config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :users 
  patch "/users/:id", to: "users#update"
  put	"/users/:id", to: "users#update"
  get "/cadastro", to: "users#new"
  root "static_pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :password, presence: true, length: {minimum: 6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :value)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :impede_logado, only: [:new, :create]
    
    def  new
    end

    def create
        user = User.find_by(email: params[:email])
        if user && user.authenticate(params[:password])
            log_in(user)
            redirect_to user
        else
            redirect_to root_path

        end
    end

    def destroy
        log_out
        redirect_to root_path
    end

    private
        def impede_logado
            if logged_in?
                redirect_to current_user
            end
        end



end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :find_user, only: [:show, :edit, :update, :destroy]
    before_action :block_unlogged, except: [:new, :create] 
    before_action :block_logged, only: [:new, :create]
    before_action :block_users, only: [:index]
    before_action :block_intruder,only: [:show, :create]


    def new
        @user = User.new
    end

    def edit
    end  

    def create
        @user =  User.new(user_params)

        if @user.save
            redirect_to root_path

        else
            render "new"
        end
    end

    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end

    def update
        if @user.update(user_params)
            redirect_to @user
        else
            render "edit"
        end
    
    end

    private

        def user_params
            params.require(:user).permit( :name, :email, :telephone, :password, :password_confirmation)
        end

        def find_user
            @user = User.find(params[:id])
        end

        def block_unlogged
            if !logged_in?
                redirect_to root_path
            end
        end
        
        def block_users
            if !is_admin?
                redirect_to root_path
            end
        end


        def block_logged
            if logged_in?
                redirect_to current_user
            end
        end

        def block_intruder
            if logged_in? && !(current_user.id == @user.id) && !is_admin?
                redirect_to current_user
            end
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        if session[:user_id]
            if @current_user.nil?
                @current_user = User.find_by(id: session[:user_id])
            else
                @current_user
            end
        end
    end

    def logged_in? 
        !current_user.nil?
    end

    def is_admin?
        @current_user = User.find_by(admin: true)
        if @current_user
            return true
        else
            return false
        end
    end


    def log_out
        session.delete(:user_id)
        @current_user = nil
    end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PeDePizza</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    <header>
      <%= image_tag("Logo.png") %>
      <p class="header_tittle">Pé de Pizza<p>
      <ul>
        <li><%= link_to "Home", root_path, class: "nav_text" %></li>
        <li><a href="#" class="nav_text">Sobre nós</a></li>
        <li><a href="#" class="nav_text">Cardapio</a></li>
        <li><a href="#" class="nav_text">Contato</a></li>
      </ul>
      <% if not logged_in? %>
        <%= render  "sessions/new" %>
      <% end %>
      <% if logged_in? %>
        <div class="profile">
          <%= link_to  "#{@current_user.name}, ", current_user %>  
          <%= link_to "Log out", logout_path, method: :delete  %>
        <div>
      <% end %>
    </header> 

    <%= yield %>
    
    <footer>
        <p class="footer_title">Siga nos</p>
        <div class="contact">
          <%= image_tag  "whatsapp.png" %>
          <%= image_tag  "facebook.png" %>
          <%= image_tag  "instagram.png" %>

    </footer>
    <p class="copyright">Copyright 2019-IN Junior</p>

  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.number_field :value %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.value %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Value:</strong>
  <%= @product.value %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/static_pages/home.html.erb
<div class="background">
</div>

<div class="about_us"> 
    <div class="icon_left"></div>
    <div class="icon_right"></div>
    <div class="large_square">
        <div class="small_square">
            <div class="about_text">
                <p id="about_tittle">Sobre nós</p>
                <p id="about_content">
                    The quick, brown fox jumps over a lazy dog. DJs flock
                    by when MTV ax quiz prog. Junk MTV quiz graced by fox whelps. 
                    Bawds jog, flick quartz, vex nymphs.
                </p>
            </div>
        </div>
    </div>
</div>


<div class="food_menu">
    <p class="food_menu_title">Nosso Cardápio</p>
    <ul>
        <li class="food_menu_items">
           <%= image_tag  "chocolate_pizza.png" %>
            <a href="#" class="food_menu_text">Pizza doce</a>
        </li>
        <li class="food_menu_items">
            <%= image_tag  "pizza.png" %>
            <a href="#" class="food_menu_text">Pizza salgada</a>
        </li>
        <li class="food_menu_items">
            <%= image_tag  "wine.png" %>
            <a href="#" class="food_menu_text">Vinhos</a>
        </li>
    </ul>
</div>

app/views/users/_form.html.erb
<div class="register_page">
    
    <div class="register_form">
        <%= form_for(@user) do |form| %>

            <div class="field">
                <%= form.label :name, "Nome" %>
                <%= form.text_field :name %>
            </div>
            
            <div class="field">
                <%= form.label :email, "Email" %>
                <%= form.email_field :email %>
            </div>
                
            <div class="field">
                <%= form.label :telephone, "Telefone" %>
                <%= form.telephone_field :telephone %>
            </div>

            <div class="field">
                <%= form.label :password, "Senha" %>
                <%= form.password_field :password %>
            </div>
            
            <div class="field">
                <%= form.label :password_confirmation, "Confirmar senha" %>
                <%= form.password_field :password_confirmation %>
            </div>

            <div class="actions">
                <%= form.submit "Cadastrar"%>
            </div>
        <% end %>
    </div>
</div>

app/views/users/edit.html.erb
<h1 class="greeting">Edite suas informações</h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', root_path %> 

app/views/users/new.html.erb
<h1 class="greeting">Cadastre-se<h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<div class="profile_page">
    <h1>Perfil<h1>
    <div class="profile_info">
        nome: <%= @user.name%>
    </div>
    <div class="profile_info">
        email: <%= @user.email %>
    </div>
    <div class="profile_info"> 
        telefone: <%= @user.telephone %>
    </div>


    <%= link_to  "Mostrar Usuarios |", users_path, class: "edit_link" %>
    <%= link_to 'Editar', edit_user_path(current_user), class: "edit_link"%>
</div>